name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build -x test

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/re-shopping-cart-web-app:${{ github.sha }} .
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/re-shopping-cart-web-app:latest .

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/re-shopping-cart-web-app:${{ github.sha }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/re-shopping-cart-web-app:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Stop and remove existing container
            docker stop re-shopping-cart-web-app || true
            docker rm re-shopping-cart-web-app || true
            
            # Pull latest image
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/re-shopping-cart-web-app:latest
            
            # Run new container
            docker run -d \
              --name re-shopping-cart-web-app \
              --restart unless-stopped \
              -p 8080:8080 \
              --env-file .env.prod \
              ${{ secrets.DOCKERHUB_USERNAME }}/re-shopping-cart-web-app:latest
